services:
  postgres:
    image: postgres:16-alpine
    container_name: procert-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: procert
      POSTGRES_PASSWORD: procert
      POSTGRES_DB: procert
      TZ: America/Sao_Paulo
    ports:
      - '5433:5432'
    volumes:
      - procert-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U procert -d procert']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: procert-adminer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  procert-pgdata:
